### ISSUE TITLE
How to find you app.py file

### ISSUE THREAD

**Issue by molyswu** [xyjigsaw/Knowledge-Graph-And-Visualization-Demo#1]
Hi,
  I didn't find your app.py file。

molys wu

**Comment by xyjigsaw** [comment]
The repository includes 4 independent projects. app.py belongs to KG-Search-Flask. You can find it [here](https://github.com/xyjigsaw/Knowledge-Graph-And-Visualization-Demo/blob/master/KG-Search-Flask/app.py).
