### ISSUE TITLE
Neo4j-3D无法运行

### ISSUE THREAD

**Issue by Zhang-JiaYu** [xyjigsaw/Knowledge-Graph-And-Visualization-Demo#2]
运行时会报错：
Error: Unknown Bolt protocol version: 0
    at new n (neo4j-color-min.js:17)
    at t (neo4j-color-min.js:17)
    at l._ch.onmessage (neo4j-color-min.js:18)
    at WebSocket._ws.onmessage (neo4j-color-min.js:18)
这和系统有关吗？您用的是Mac吗？
﻿我也看到您在博客上说翻墙试一下，也进行了尝试，结果也会报错。
​

**Comment by xyjigsaw** [comment]
按常理来说好像可以直接运行的，与操作系统无关吧，确实是需要翻墙；你可以换个浏览器，如果还不行你看看这个js的服务器是否还有服务。

**Comment by Zhang-JiaYu** [comment]
这个问题我尝试解决了一下，是这个驱动的问题。将index中的<script src="neo4j-color-min.js"></script>换成<script src="https://unpkg.com/neo4j-driver@4.0.2/lib/browser/neo4j-web.min.js"></script>就可以了，更多替换方法可以看https://neo4j.com/docs/api/javascript-driver/current/

**Comment by xyjigsaw** [comment]
好的，谢谢~
