### ISSUE TITLE
最后导入关系的时候有个小问题

### ISSUE THREAD

**Issue by fengyunzaidushi** [xyjigsaw/Knowledge-Graph-And-Visualization-Demo#4]
``
:auto USING PERIODIC COMMIT 5000
LOAD CSV WITH HEADERS FROM "file:///patient-location.csv" AS line
MATCH (FROM:PATIENT{p_id:line.p_id}), (TO:LOCATION{l_id:line.l_id})
MERGE (FROM)-[PATIENT_LOCATION: `PATIENT_LOCATION{type:"diagnosedIn"}]->(TO)`

实际patient-location.csv文件里是l_ld， 所以要修改一下。

**Comment by xyjigsaw** [comment]
Thank you for pointing out the problem.
