### ISSUE TITLE
数据库连接成功，但是在查询请求提交后，无法显示内容。后台报的是200。

### ISSUE THREAD

**Issue by 1225hao** [xyjigsaw/Knowledge-Graph-And-Visualization-Demo#5]

**Comment by xyjigsaw** [comment]
你好，请问你具体指那一块呢？

**Comment by 1225hao** [comment]
> 你好，请问你具体指那一块呢？
您好，连接成功后界面显示如下，您给的数据已经导入了，想请问一下这个该怎么办？
![截屏2023-11-06 下午4 51 46](https://github.com/xyjigsaw/Knowledge-Graph-And-Visualization-Demo/assets/95691526/a71ca6e8-37fd-488f-b13a-416f46dfe664)
![截屏2023-11-06 下午4 51 01](https://github.com/xyjigsaw/Knowledge-Graph-And-Visualization-Demo/assets/95691526/f4ce655d-4034-4683-98c5-4253d8c590a1)

**Comment by xyjigsaw** [comment]
看上去是数据没有完全导入。
